### PR TITLE
Cleanup C++ examples and fix CI

### PR DESCRIPTION
**Pull request by cmnrd**
Fixes https://github.com/lf-lang/examples-lingua-franca/issues/44
Fixes https://github.com/lf-lang/examples-lingua-franca/issues/39

### CODE REVIEW

**Comment by cmnrd** [comment]
@lhstrh I have a problem with the ROS2 setup. We need to source `source /opt/ros/*/setup.bash` before running lfc. However, it looks like the environment is not persistent between steps. Although we source the setup script in the previous step, the variables are not present in the check-lf step and thus the ROS2 installation is not detected by lfc. Do you have an idea how we can make the environment variables created in the source step, available during the check?

**Comment by lhstrh** [comment]
> @lhstrh I have a problem with the ROS2 setup. We need to source `source /opt/ros/*/setup.bash` before running lfc. However, it looks like the environment is not persistent between steps. Although we source the setup script in the previous step, the variables are not present in the check-lf step and thus the ROS2 installation is not detected by lfc. Do you have an idea how we can make the environment variables created in the source step, available during the check?

You can make particular variables available by piping them into `$GITHUB_ENV`: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable 

Would that help?

**Comment by lhstrh** [comment]
Should we merge this or would you like to fix the ROS2 problem first? You can also move it in an `experimental` directory and document that it requires stuff to be installed first. We ignore `failing` and `experimental`...

**Comment by cmnrd** [comment]
The problem is that there are multiple variables defined and I don't really know which are needed. I found a simple way to just dump all environment variables.

There is a bug in the ROS2 support of LF, which was masked by another bug in the integration test suite. It is fixed in https://github.com/lf-lang/lingua-franca/pull/1841.

**Comment by cmnrd** [comment]
I am merging this. The remaining C++ failures need to be addressed in the LF repo.

**Pull request merged**
