### PR TITLE
Add a simple chat application

### PR DESCRIPTION
**Pull request by ByeongGil-Jun**

### CODE REVIEW

**Comment by hokeun** [comment]
@edwardalee Could you please give us advice on how to address the following warning below? Thank you!

```
 --> junk/src/SimpleChat.lf:70:5
   |
69 |     input receive:string;
70 |     output send:string;
   |     ^^^^^^^^^^^^^^^^^^^ Found a path from a physical action to output for reactor "a".
The amount of delay is 0.
With centralized coordination, this can result in a large number of messages to the RTI.
Consider refactoring the code so that the output does not depend on the physical action,
or consider using decentralized coordination. To silence this warning, set the target
parameter coordination-options with a value like {advance-message-interval: 10 msec}
```

**Comment by Soroosh129** [comment]
Set `coordination-options: {advance-message-interval: 10 msec}` in the target properties as suggested :)

**Comment by hokeun** [comment]
> Set `coordination-options: {advance-message-interval: 10 msec}` in the target properties as suggested :)

Thank you, @Soroosh129 ! I missed that line.

@ByeongGil-Jun , could you add the line above to the target properties?

**Comment by ByeongGil-Jun** [comment]
@hokeun, I have added the line and pushed them.

**Review by edwardalee — APPROVED** [review]
Looks like a good start to me.  The interesting problems will arise with variable numbers of clients and dynamic joining and leaving.

**Comment by hokeun** [comment]
> Looks like a good start to me. The interesting problems will arise with variable numbers of clients and dynamic joining and leaving.

Thank you for the review & approaval!

**Comment by hokeun** [comment]
I'll be merging this as this is just an example and does not affect the LF core, but if you have comments or feedback later we'll be happy to address them in the next PR.

**Pull request merged**
